<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>1.0.2</Version>
    <PackageVersion>1.0.2</PackageVersion>
    <AssemblyVersion>1.0.2.0</AssemblyVersion>
    <FileVersion>1.0.2.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Mrbr.Service.KeyManager" Version="1.0.1" />
    <PackageReference Include="Mrbr.SourceGenerators.Common" Version="1.0.0" />
  </ItemGroup>
</Project>